### ISSUE TITLE
Rubocop too overzealous?

### ISSUE THREAD

**Issue by jyaworski** [puppet-community/modulesync_config#14]
Hello:

I've been working on the puppet-rundeck modulesync changes at https://github.com/puppet-community/puppet-rundeck/pull/134

It looks like it's failing on rubocop, but a lot of it is very benign.

1. Long lines
2. and vs &&
3. Nested functions
etc

One of the main things I'm running into is:

https://github.com/bbatsov/rubocop/issues/1238

Can we tone down Rubocop's aggression?

**Comment by jyaworski** [comment]
Also here:

https://github.com/bbatsov/rubocop/issues/947

**Comment by jyaworski** [comment]
One possible solution is to use --only-guide-cops as documented in https://github.com/bbatsov/rubocop/pull/1454

**Comment by igalic** [comment]
@jyaworski that seems like a very good idea, and is probably very much less… opinionated.!

**Comment by igalic** [comment]
@jyaworski can you add pr that changes our config to that?

**Comment by mkrakowitzer** [comment]
Can I suggest using .rubocop.yml from garethr/puppet-module-skeleton as a base?

https://github.com/garethr/puppet-module-skeleton/blob/master/skeleton/.rubocop.yml

**Comment by igalic** [comment]
there are a couple of those i don't entirely agree with… such as:
```yaml
Style/RegexpLiteral:
  Enabled: false
```

that's literally the reason i started this whole thing ;)

**Comment by jyaworski** [comment]
One solution is to add --fail-level and set it to a sane default; say 'E'. Maybe add a parameter to .sync.yml to toggle it per-project if you want? How does that sound?

````
joseph.yaworski@jyaworski-mbpr ~/puppet-rundeck (git)-[modulesync] % rubocop
...
25 files inspected, 121 offenses detected
joseph.yaworski@jyaworski-mbpr ~/puppet-rundeck (git)-[modulesync] % echo $?                                                                                                                                                             :(
1

joseph.yaworski@jyaworski-mbpr ~/puppet-rundeck (git)-[modulesync] % rubocop --fail-level=E
...
25 files inspected, 121 offenses detected
joseph.yaworski@jyaworski-mbpr ~/puppet-rundeck (git)-[modulesync] % echo $?                                                                                                                                                             
0
````

**Comment by mkrakowitzer** [comment]
OK so my initial thoughts on trying to get my spec tests reformatted to meet the current requirements is that I will still be reformatting perfectly working code in about 2 weeks from now, and this is only one project! I have literally spent an entire evening formatting text and I am only about 50% done. Rubocops autocorrect is a disaster, so that did not even help.

We need a more sane config file in order for any module to make rubocop a viable option or force it to exist 0 as per @jyaworski previous comment.

**Comment by igalic** [comment]
Agreed.
the defaults are impossible to comply with, especially in rspec tests.

**Comment by daenney** [comment]
I don't think long lines or `and` vs `&&` is pretty benign. Long lines are hard to read and the longer they get the more complicated expressions they usually contain.

`&&` vs `and` are pretty similar in Ruby but their difference is in binding strength / operator precedence so we should care about those. The style guide is pretty clear on this too:

> Use &&/|| for boolean expressions, and/or for control flow. (Rule of thumb: If you have to use outer parentheses, you are using the wrong operators.)

**Comment by igalic** [comment]
@jyaworski i also agree with that, however, rubocop's default auto_correct behaviour is awful…

**Comment by daenney** [comment]
Then don't autocorrect/use the fixers, just let it complain about it and fix it yourself :smile:

**Comment by igalic** [comment]
fixing thousands of lines code isn't really my idea of fun :P

**Comment by daenney** [comment]
It's not thousands of lines, it's one module at a time and not all modules, far from all, have native types and providers. And new code can start out directly by adhering to this. There's also no need to go full on zealot on it and fix everything now now now.

**Comment by igalic** [comment]
when i say thousands of lines of code, i specifically mean rspec tests.
but yes, you are right.

**Comment by danzilio** [comment]
Definitely agree with @daenney on `and` vs. `&&`. Also, don't forget about control comments for exceptions. Sometimes breaking with the style guide on a single line makes sense for readability or maintainability. You can disable a cop for a single line by adding a trailing control comment like this: `# rubocop:disable RULENAME`. This should obviously be used judiciously, but we shouldn't be pedantic.

**Comment by igalic** [comment]
after merging #21 i think we've got some better fit…

**Comment by igalic** [comment]
now, if only we had some kind of trigger that would run msync update for us…

**Comment by jyaworski** [comment]
I just resynced https://github.com/puppet-community/puppet-rundeck/pull/139 and I'm getting different errors. Still looking into them.

**Comment by jyaworski** [comment]
All right. Lots of refactoring later and I'm back to a smaller number of rubocop errors.

@daenney and @danzilio: I'm not super well-versed in Ruby, so maybe I spoke out of naivete with the and/&& thing. Long lines I understand the frustration as well. However, I share @igalic's general frustration surrounding rspec tests; that's where all of that PR I mentioned is failing, and some of them are non-trivial to fix. Do we really want to lint spec files in that case?

**Comment by daenney** [comment]
That is a good question. I'm not convinced the spec tests have to adhere to all the Rubocop madness. It might be worth only loading rubocop-rspec for the spec/ directory and a few basic other cops.

**Comment by mkrakowitzer** [comment]
Personally I think it makes the spec tests harder to read: https://github.com/puppet-community/puppet-stash/pull/99/files

**Comment by jyaworski** [comment]
All right; I've turned off a few cops in #24.

**Comment by igalic** [comment]
@mkrakowitzer i can't even tell the difference anymore ~_~
@jyaworski merged

**Comment by logicminds** [comment]
We need an exclusion for these kinds of errors.  I don't agree with rubocop

```
lib/puppet/parser/functions/default_content.rb:10:1: C: Align ) with (.
) do |args|
^
lib/puppet/parser/functions/dump_args.rb:11:1: C: Align ) with (.
) do |args|

```

**Comment by daenney** [comment]
Well, just because one person doesn't agree is not a good enough reason to exclude. Why do you disagree and perhaps share a few screenshots of code that is more legible in your case than what rubocop recommends?

**Comment by igalic** [comment]
i'm pretty and sure i've excluded those ;)
@daenney they make most of our rspec code completely unreadable

**Comment by logicminds** [comment]
@daenney this is the default way of defining puppet functions.  example: https://github.com/logicminds/puppet-extlib/commit/fc46c637371105de23a92d61c7f5ea4fb143497d#diff-e24a4c8f84f47be4ba90e4572ed66e18R11

Every puppet function in puppet core is defined this way.

**Comment by jyaworski** [comment]
I just linked from a PR where it's complaining about module comments. Definitely not something worth failing on.

**Comment by igalic** [comment]
@jyaworski any idea what needs to change to make it pass?

**Comment by jyaworski** [comment]
@igalic yes.

https://github.com/puppet-community/modulesync_config/pull/35
