### ISSUE TITLE
explicitly mention and link our Code of Conduct

### ISSUE THREAD

**Issue by igalic** [puppet-community/modulesync_config#15]
We are using the [Contributor Covenant](http://contributor-covenant.org/) code of conduct, and should explicitly [link](http://contributor-covenant.org/version/1/2/0/) to it in our [CONTRIBUTING.md](https://github.com/puppet-community/modulesync_config/blob/master/moduleroot/CONTRIBUTING.md)

**Comment by ffrank** [comment]
Just realized when reviewing #25 by @bravepeanut that the link should perhaps point towards our own CoC (based on Contributor Covenant)?
