### ISSUE TITLE
Puppet 4 and Augeas

### ISSUE THREAD

**Issue by jyaworski** [puppet-community/modulesync_config#26]
Hello:

I'm working on https://github.com/puppet-community/puppet-rundeck/pull/134 and the module was recently modified to use augeas. Augeas isn't included by default in puppet 4, so I added the gems to the gemfile. Travis is unable to build them because libaugeas isn't installed.

Is there a better way to do this than enabling sudo and installing libaugeas?

**Comment by liamjbennett** [comment]
I have run into this issue a few times with ruby 2.x. There is no way, that I am aware of installing augeas without installing the ruby package and having libaugeas-dev package installed.

https://github.com/opentable/puppet-puppetversion/blob/master/manifests/init.pp#L78:L90

**Comment by igalic** [comment]
I'm 😲 and 😕.

**Comment by igalic** [comment]
ooooh. puppet-agent probably has it bundled, but on Travis we install from gem.
